name: 'PR to DEV'

on:
  push:
    branches:
      - 'feature/*'       # matches every branch containing a single '/'

jobs:
  terraform:
    name: 'Open PR to DEV'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      APPLICATON_NAME: fiap-api

    defaults:
      run:
        shell: bash
        working-directory: ./infra

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init -backend-config="key=$APPLICATON_NAME-develop.tfstate"

      - name: Terraform Plan
        run: terraform plan -var 'environment=develop' -input=false

      - name: Create Pull Request to Develop
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "develop"